for review: 02-javascript-data-types
js-tasks-ru/js-20200821-3_roman1gan pull request #2
Opened 2020-08-31 18:13 UTC by afedevon

2020-08-31 18:19 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-09-01 10:38 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete result[key];
очень нежелательно использовать `delete` даже если Вы предварительно скопировали объект. При наличии вложенных объектов это может привести к ошибкам

2020-09-01 10:40 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (key in result) {
оператор `in` вернет булево значение как для собственных так и для унаследованных свойств объекта, к примеру:
```
"toString" in ({}) // true
```
А в большинстве случаев нас интересуют именно собственные свойства объекта__

2020-09-01 10:41 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
good 👍

2020-09-01 10:41 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-09-01 11:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-03 14:37 UTC, dosandk approved these changes
good 👍

2020-09-03 14:38 UTC, merged